null
java.lang.NullPointerException: Cannot invoke "com.iu.s1.bankbook.BankBookService.getList(javax.servlet.http.HttpServletRequest)" because "this.bankBookService" is null